### ISSUE TITLE
How to use this tool?

### ISSUE THREAD

**Issue by loukach** [shenril/owasp-asvs-checklist#4]
Hi, are you guys using this framework only to check if security verifications are performed or also to check the results of these controls?

**Comment by shenril** [comment]
Hello @lucasgros 
Thanks for getting in touch 

We use this checklist as an attachment for each release to see the evolution of security through our product lifecycle
Some parts of it are actually automated but the results are always attached to new releases deployed

Regarding new projects, we also use it to validate security at the pre-launch phase

When we discover issues in both cases, a ticket is created at the development side to fix it or work on countermeasures. 

Does this answer your question? Don't hesitate to tell me if you need more details on any part of the process

**Comment by loukach** [comment]
Hi @shenril, thanks for the feedback, I've come across the two visions I was presenting in my initial question and curious to see how other people are using this tool. 
I our team, we focus on measuring how the application security requirements are controled more than getting the results of these controls. The results of such controls, we get then from SAST for example, and are trying to automate this crosscheck as much as possible.
And you?
Thanks for your contribution and provide this discussion space.

**Comment by shenril** [comment]
@loukach 
I have to say that, in order to be able to follow the evolution consistently we moved this spreadsheet to a cloud service like Google docs, and we fill most of it automatically through API calls and results of different tools. 
However, a fair 50% still remains manual at this point 
Depending on version 4.0.0 that will come soon, we will re-evaluate to see if we can automate more.
We're struggling around the verification tools actually, there are a lot of them doing only a subset of what we want, so we end up with a whole stack to maintain. 
Regarding the discussion space, I would encourage you to join the OWASP Slack channels if you can 
https://owasp.slack.com/
There is a dedicated room for ASVS and practices around their tools
I'd be happy to discuss more around practices and technical subject if you have further questions :)

**Comment by shenril** [comment]
If there are no other questions I'll close this issue
Feel free to open a new one if something pops up your mind ;)
